// <auto-generated />
using System;
using CMS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CMS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224104156_AddThumbAndViewToContentPage")]
    partial class AddThumbAndViewToContentPage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CMS.Models.ContentPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("ChuyenMucId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("HasSidebar")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenMucId");

                    b.ToTable("ContentPages");
                });

            modelBuilder.Entity("CMS.Models.NavigationMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChuyenMucId")
                        .HasColumnType("integer");

                    b.Property<int?>("ContentPageId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenMucId");

                    b.HasIndex("ContentPageId");

                    b.HasIndex("ParentId");

                    b.ToTable("NavigationMenus");
                });

            modelBuilder.Entity("CMS.Models.SidebarItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<int?>("ChuyenMucId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int?>("ContentPageId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("MenuId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenMucId");

                    b.HasIndex("ContentPageId");

                    b.HasIndex("MenuId");

                    b.ToTable("SidebarItems");
                });

            modelBuilder.Entity("CMS.Models.TaiKhoan", b =>
                {
                    b.Property<string>("TenDangNhap")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TenDangNhap");

                    b.ToTable("TaiKhoan");
                });

            modelBuilder.Entity("YourProjectName.Models.ChuyenMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("ChuyenMucs");
                });

            modelBuilder.Entity("CMS.Models.ContentPage", b =>
                {
                    b.HasOne("YourProjectName.Models.ChuyenMuc", "ChuyenMuc")
                        .WithMany("ContentPages")
                        .HasForeignKey("ChuyenMucId");

                    b.Navigation("ChuyenMuc");
                });

            modelBuilder.Entity("CMS.Models.NavigationMenu", b =>
                {
                    b.HasOne("YourProjectName.Models.ChuyenMuc", "ChuyenMuc")
                        .WithMany("Menus")
                        .HasForeignKey("ChuyenMucId");

                    b.HasOne("CMS.Models.ContentPage", "LinkedPage")
                        .WithMany()
                        .HasForeignKey("ContentPageId");

                    b.HasOne("CMS.Models.NavigationMenu", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChuyenMuc");

                    b.Navigation("LinkedPage");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("CMS.Models.SidebarItem", b =>
                {
                    b.HasOne("YourProjectName.Models.ChuyenMuc", "ChuyenMuc")
                        .WithMany("Sidebars")
                        .HasForeignKey("ChuyenMucId");

                    b.HasOne("CMS.Models.ContentPage", "ContentPage")
                        .WithMany("SidebarItems")
                        .HasForeignKey("ContentPageId");

                    b.HasOne("CMS.Models.NavigationMenu", "Menu")
                        .WithMany("SidebarItems")
                        .HasForeignKey("MenuId");

                    b.Navigation("ChuyenMuc");

                    b.Navigation("ContentPage");

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("CMS.Models.ContentPage", b =>
                {
                    b.Navigation("SidebarItems");
                });

            modelBuilder.Entity("CMS.Models.NavigationMenu", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("SidebarItems");
                });

            modelBuilder.Entity("YourProjectName.Models.ChuyenMuc", b =>
                {
                    b.Navigation("ContentPages");

                    b.Navigation("Menus");

                    b.Navigation("Sidebars");
                });
#pragma warning restore 612, 618
        }
    }
}
